controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::index
